-- YepBio Parkinson's/neuro and life-sciences prospect list.  URLs are left
-- null where an official destination is ambiguous; the app supplies a safe
-- institution search link rather than storing an unverified website.
do $$
declare v_admin uuid;
begin
  select id into v_admin from public.profiles where role = 'lvnc_admin' order by created_at limit 1;
  insert into public.potential_meetings
    (organisation_id, institution_name, category, external_url, created_by)
  select '99999999-9999-4999-8999-999999999998'::uuid, v.name, v.category, v.url, v_admin
  from (values
    ('Parkinson''s Research Institute Affiliation','Parkinson''s research','https://www.parkinsons.org.uk/'),
    ('Neuro VC','Neuroscience investor',null),
    ('RYSE Asset Management','Neuroscience investor','https://www.ryseam.com/'),
    ('re.Mind Capital','Neuroscience investor',null),
    ('Cure Parkinson''s Foundation-adjacent researchers','Parkinson''s research',null),
    ('NHS ICB(s)','NHS / clinical pathway','https://www.england.nhs.uk/'),
    ('SV Health Investors','Life-sciences investor','https://svhealthinvestors.com/'),
    ('Advent Life Sciences','Life-sciences investor','https://adventls.com/'),
    ('Epidarex Capital (Edinburgh)','Life-sciences investor','https://www.epidarex.com/'),
    ('Syncona','Life-sciences investor','https://www.synconaltd.com/'),
    ('Cambridge Innovation Capital','Life-sciences investor','https://www.cicplc.co.uk/'),
    ('LifeArc','Life-sciences translational partner','https://www.lifearc.org/'),
    ('Parkinson''s UK','Patient / research network','https://www.parkinsons.org.uk/'),
    ('UK Dementia Research Institute','Neuroscience research','https://www.ukdri.ac.uk/'),
    ('UCL Queen Square Institute of Neurology','Neuroscience research','https://www.ucl.ac.uk/ion/'),
    ('King''s College London (IoPPN)','Neuroscience research','https://www.kcl.ac.uk/ioppn'),
    ('Medical Research Council (MRC)','Public research funder','https://www.ukri.org/councils/mrc/'),
    ('Oxford Tech Transfer','University technology transfer','https://innovation.ox.ac.uk/'),
    ('4BIO Capital','Life-sciences investor','https://4biocapital.com/'),
    ('Parkwalk Advisors','University spinout investor','https://parkwalkadvisors.com/'),
    ('Oxford Science Enterprises','Life-sciences investor','https://oxfordscienceenterprises.com/'),
    ('Longwall Ventures','Life-sciences investor','https://www.longwallventures.com/'),
    ('LifeArc Ventures','Life-sciences investor','https://www.lifearc.org/'),
    ('Sofinnova Partners','Life-sciences investor','https://sofinnovapartners.com/'),
    ('Forbion','Life-sciences investor','https://www.forbion.com/'),
    ('HealthCap','Life-sciences investor','https://healthcap.eu/'),
    ('EQT Life Sciences','Life-sciences investor','https://eqtgroup.com/about/our-businesses/eqt-life-sciences'),
    ('Novo Holdings','Life-sciences investor','https://novo.com/'),
    ('Kurma Partners','Life-sciences investor','https://www.kurmapartners.com/'),
    ('Ysios Capital','Life-sciences investor','https://ysioscapital.com/'),
    ('M Ventures','Corporate life-sciences investor','https://www.m-ventures.com/'),
    ('Novartis Venture Fund','Corporate life-sciences investor','https://www.novartis.com/research-development/novartis-venture-fund'),
    ('Roche Venture Fund','Corporate life-sciences investor','https://www.roche.com/innovation/venture-fund'),
    ('Pfizer Ventures','Corporate life-sciences investor','https://www.pfizer.com/science/innovation/pfizer-ventures'),
    ('Sanofi Ventures','Corporate life-sciences investor','https://www.sanofi.com/en/our-science/venture-capital'),
    ('UCB Ventures','Corporate life-sciences investor','https://www.ucb.com/innovation/ventures'),
    ('Boehringer Ingelheim Venture Fund','Corporate life-sciences investor','https://www.boehringer-ingelheim.com/innovation/venture-fund'),
    ('Johnson & Johnson Innovation','Corporate life-sciences partner','https://jnjinnovation.com/'),
    ('AbbVie Ventures','Corporate life-sciences investor','https://www.abbvie.com/partnering/ventures.html'),
    ('Amgen Ventures','Corporate life-sciences investor','https://www.amgen.com/about/innovation/venture-capital'),
    ('Takeda Ventures','Corporate life-sciences investor','https://www.takeda.com/what-we-do/partnerships/'),
    ('Eli Lilly Ventures','Corporate life-sciences investor','https://www.lilly.com/innovation'),
    ('Biogen Ventures','Corporate life-sciences investor','https://www.biogen.com/'),
    ('Merck Ventures','Corporate life-sciences investor','https://www.merckgroup.com/en/company/innovation/venture-capital.html'),
    ('OrbiMed','Life-sciences investor','https://www.orbimed.com/'),
    ('RA Capital','Life-sciences investor','https://www.racap.com/'),
    ('F-Prime Capital','Life-sciences investor','https://fprimecapital.com/'),
    ('Deerfield','Life-sciences investor','https://www.deerfield.com/'),
    ('Samsara BioCapital','Life-sciences investor','https://samsarabio.com/'),
    ('MPM Capital','Life-sciences investor','https://mpmcapital.com/'),
    ('Third Rock Ventures','Life-sciences investor','https://thirdrockventures.com/'),
    ('Atlas Venture','Life-sciences investor','https://www.atlasventure.com/'),
    ('Omega Funds','Life-sciences investor','https://www.omegafunds.net/'),
    ('Venrock','Life-sciences investor','https://www.venrock.com/'),
    ('ARCH Venture Partners','Life-sciences investor','https://archventure.com/'),
    ('Sofinnova MD Start','Life-sciences investor','https://sofinnovapartners.com/'),
    ('BGF Early Stage','Life-sciences investor','https://www.bgf.co.uk/'),
    ('British Patient Capital','Patient capital investor','https://www.britishpatientcapital.co.uk/'),
    ('Future Fund: Breakthrough','Public growth finance','https://www.gov.uk/government/publications/future-fund-breakthrough'),
    ('Schroders Capital','Institutional investor','https://www.schroders.com/'),
    ('M&G Catalyst','Growth / impact investor','https://www.mandg.com/'),
    ('IP Group','University spinout investor','https://www.ipgroupplc.com/'),
    ('Northern Gritstone','Deep-tech investor','https://northerngritstone.com/'),
    ('Abingworth','Life-sciences investor','https://www.abingworth.com/'),
    ('Medicxi','Life-sciences investor','https://medicxi.com/'),
    ('SR One Capital Management','Life-sciences investor','https://srone.com/'),
    ('UK Innovation & Science Seed Fund (UKI2S)','Public seed finance','https://www.uki2s.com/'),
    ('Aescap Venture','Life-sciences investor','https://aescap.com/'),
    ('Amadeus Capital Partners','Deep-tech investor','https://amadeuscapital.com/'),
    ('Andera Partners','Life-sciences investor','https://www.anderapartners.com/'),
    ('Apeiron Investment Group','Technology investor','https://www.apeiron-investment.com/'),
    ('BioGeneration Ventures','Life-sciences investor','https://www.biogenerationventures.com/'),
    ('Biogen (corporate strategic investment)','Corporate life-sciences partner','https://www.biogen.com/'),
    ('Calculus Capital','Life-sciences investor','https://www.calculuscapital.com/'),
    ('Gilde Healthcare','Life-sciences investor','https://gildehealthcare.com/'),
    ('Kreos Capital','Growth investor','https://www.kreoscapital.com/'),
    ('LSP (Life Sciences Partners)','Life-sciences investor','https://www.lspvc.com/'),
    ('Lilly Ventures / Lilly Asia Ventures','Corporate life-sciences investor','https://www.lilly.com/innovation'),
    ('Mercia Asset Management','Venture investor','https://www.mercia.co.uk/'),
    ('Molten Ventures','Deep-tech investor','https://www.moltenventures.com/'),
    ('Oxford Sciences Innovation','University spinout investor','https://www.oxfordsciencesinnovation.com/'),
    ('Perceptive Advisors','Life-sciences investor','https://www.perceptiveadvisors.com/'),
    ('Pureos Bioventures','Life-sciences investor','https://pureos.com/'),
    ('RTW Investments','Life-sciences investor','https://www.rtwfunds.com/'),
    ('Scottish Investment Bank / Scottish Enterprise','Public growth finance','https://www.scottish-enterprise.com/'),
    ('Seroba Life Sciences','Life-sciences investor','https://www.seroba-lifesciences.com/'),
    ('Talis Capital','Technology investor','https://www.taliscapital.com/'),
    ('Wellington Partners','Life-sciences investor','https://www.wellington-partners.com/')
  ) as v(name, category, url)
  where not exists (
    select 1 from public.potential_meetings existing
    where existing.organisation_id = '99999999-9999-4999-8999-999999999998'::uuid
      and lower(trim(existing.institution_name)) = lower(trim(v.name))
  );
end $$;
