-- Additional verified UK opportunities for YepBio between 28 September and
-- 23 October 2026. These are optional/recommended choices, intentionally
-- visible only to YepBio, and are idempotent by title + start date.
do $$
declare
  yepbio_id uuid;
  admin_id uuid;
begin
  select id into yepbio_id from public.organisations where slug = 'yepbio';
  select id into admin_id from public.profiles where role = 'lvnc_admin' order by created_at limit 1;

  if yepbio_id is null then raise exception 'YepBio organisation is missing.'; end if;
  if admin_id is null then raise exception 'No LVCN admin profile exists. Sign in once as an LVCN admin, then deploy this migration.'; end if;

  with events (title, description, starts_at, ends_at, time_precision, location, event_url, cost_type, cost_note, priority, fit, next_action, source_note) as (
    values
      ('North West London Research Symposium 2026', 'Imperial Academic Health Science Centre research symposium. A route into North West London clinical-academic research and translational-care conversations.', '2026-09-30T12:00:00+01:00'::timestamptz, '2026-09-30T17:00:00+01:00'::timestamptz, 'exact'::public.time_precision, 'Copthorne Tara Hotel, South Kensington, London', 'https://imperialbrc.nihr.ac.uk/events/', 'free'::public.cost_type, 'Free; registration required.', 'conditional'::public.item_priority, 'Useful for mapping Imperial AHSC research contacts and NHS-academic collaboration routes.', 'Register only if a neuroscience, biomarker or early-phase-study contact can be identified.', 'YepBio UK opportunities | NW London Research Symposium'),
      ('Brainbox Initiative Conference 2026', 'Neuroimaging and non-invasive brain-stimulation conference. Relevant for neuroimaging, neurophysiology and biomarker-methodology conversations.', '2026-10-01T00:00:00+01:00'::timestamptz, '2026-10-03T00:00:00+01:00'::timestamptz, 'all_day'::public.time_precision, 'Wellcome Collection, London', 'https://brainbox-initiative.com/conference', 'unknown'::public.cost_type, 'Registration and delegate rate to verify.', 'strong_option'::public.item_priority, 'High-signal neuroscience audience relevant to Parkinson''s disease mechanism, imaging and biomarker strategy.', 'Review the agenda and pre-arrange 2-3 neuroimaging or neurophysiology meetings.', 'YepBio UK opportunities | Brainbox Initiative'),
      ('International Single Cell Mass Spectrometry Conference and BMSS Single Cell SIG Meeting 2026', 'King''s College London conference on single-cell and spatial omics, including neuroscience and precision medicine.', '2026-10-06T08:30:00+01:00'::timestamptz, '2026-10-09T18:00:00+01:00'::timestamptz, 'exact'::public.time_precision, 'Great Hall, Strand Campus, King''s College London', 'https://www.kcl.ac.uk/events/international-single-cell-mass-spectrometry-conference-and-bmss-single-cell-sig-meeting-2026', 'unknown'::public.cost_type, 'Registration open; delegate rate to verify.', 'must_pursue'::public.item_priority, 'Direct relevance to PARIS biomarker assay strategy, single-cell biology and precision-medicine collaborators.', 'Identify neuroscience, spatial-omics and clinical-biomarker speakers; request short meetings before registration.', 'YepBio UK opportunities | KCL Single Cell MS'),
      ('Imperial Bioengineering Research Showcase 2026', 'Open, free Imperial College research showcase with talks, posters and networking across bioengineering, including neuromechanics and rehabilitation technology.', '2026-10-12T11:00:00+01:00'::timestamptz, '2026-10-12T14:00:00+01:00'::timestamptz, 'exact'::public.time_precision, 'The Arena, Scale Space, White City Campus, London', 'https://www.imperial.ac.uk/events/212872/bioengineering-research-showcase-2026/', 'free'::public.cost_type, 'Free; registration required.', 'strong_option'::public.item_priority, 'Compact, accessible route to Imperial researchers and White City translational ecosystem contacts.', 'Register and target researchers with neurotechnology, biomarker, modelling or translational interests.', 'YepBio UK opportunities | Imperial Bioengineering Showcase'),
      ('The Bioengineering Lecture 2026', 'Imperial College flagship Department of Bioengineering lecture, open to all and followed by the wider showcase programme.', '2026-10-12T17:30:00+01:00'::timestamptz, '2026-10-12T18:30:00+01:00'::timestamptz, 'exact'::public.time_precision, 'Molecular Sciences Research Hub, White City Campus, London', 'https://www.imperial.ac.uk/events/211811/the-bioengineering-lecture-2026/', 'free'::public.cost_type, 'Free; registration required.', 'conditional'::public.item_priority, 'A low-friction evening networking opportunity with Imperial bioengineering community.', 'Attend alongside the afternoon showcase only if the agenda allows meaningful researcher introductions.', 'YepBio UK opportunities | Imperial Bioengineering Lecture'),
      ('SBNS 100 2026', 'Society of British Neurological Surgeons centenary conference across neuroscience, clinical research, neurorehabilitation and related disciplines.', '2026-10-12T00:00:00+01:00'::timestamptz, '2026-10-17T00:00:00+01:00'::timestamptz, 'all_day'::public.time_precision, 'QEII Conference Centre, Westminster, London', 'https://www.sbns.org.uk/event-calendar.html', 'unknown'::public.cost_type, 'Registration and industry-access route to verify.', 'strong_option'::public.item_priority, 'Dense UK neuroscience and clinical ecosystem; relevant for Parkinson''s clinical-network, trial-design and biomarker conversations.', 'Select a single day around a confirmed relevant session and arrange clinician/researcher introductions before registering.', 'YepBio UK opportunities | SBNS 100'),
      ('Reframing Precision Medicine: Innovation to Implementation', 'Nature Conference on genomics, multi-omics, clinical sciences and data-driven personalised care.', '2026-10-13T00:00:00+01:00'::timestamptz, '2026-10-16T00:00:00+01:00'::timestamptz, 'all_day'::public.time_precision, 'The Royal Institution, London', 'https://precision-medicine.conferences.nature.com/', 'paid'::public.cost_type, 'Paid registration; check current delegate options.', 'must_pursue'::public.item_priority, 'Strong strategic fit for PARIS biomarker development, patient stratification and translational evidence planning.', 'Prioritise the biomarker, multi-omics and clinical-implementation sessions; request relevant academic and industry meetings.', 'YepBio UK opportunities | Reframing Precision Medicine'),
      ('South Central Parkinson''s Research Event 2026', 'Parkinson''s UK in-person research event covering current research updates and interactive activities.', '2026-10-20T10:00:00+01:00'::timestamptz, '2026-10-20T16:00:00+01:00'::timestamptz, 'exact'::public.time_precision, 'Hampshire Court Hotel and Spa, Basingstoke', 'https://www.parkinsons.org.uk/research/get-involved/research-events', 'unknown'::public.cost_type, 'Registration details to verify.', 'strong_option'::public.item_priority, 'Direct Parkinson''s research and lived-experience context for biomarker, trial-design and patient-involvement planning.', 'Confirm company-attendance suitability with Parkinson''s UK and attend with a listening and relationship-building agenda.', 'YepBio UK opportunities | Parkinson''s UK South Central Research Event'),
      ('Cambridge Stem Cell Institute International Seminar', 'Cambridge Stem Cell Institute flagship international seminar series, with a research audience from Cambridge and beyond.', '2026-10-21T12:00:00+01:00'::timestamptz, '2026-10-21T13:00:00+01:00'::timestamptz, 'exact'::public.time_precision, 'Jeffrey Cheah Biomedical Centre lecture theatre, Cambridge', 'https://www.stemcells.cam.ac.uk/events/international-seminars', 'unknown'::public.cost_type, 'Registration is listed by the organiser; confirm attendance arrangements.', 'conditional'::public.item_priority, 'Useful Cambridge research-network touchpoint for cell biology, disease mechanisms and translational collaboration.', 'Attend only if paired with pre-arranged Cambridge neuroscience, biomarker or investor meetings.', 'YepBio UK opportunities | Cambridge Stem Cell Seminar'),
      ('Complexity of Neural Function: The Brain in Charge', 'Royal Society neuroscience meeting on brain function, neural disease mechanisms and genetics.', '2026-10-22T00:00:00+01:00'::timestamptz, '2026-10-23T00:00:00+01:00'::timestamptz, 'all_day'::public.time_precision, 'The Royal Society, London', 'https://genetics.org.uk/events/complexity-of-neural-function-the-brain-in-charge/', 'unknown'::public.cost_type, 'Registration deadline listed as 12 October 2026; verify current availability.', 'strong_option'::public.item_priority, 'Direct neuroscience and neural-disease-mechanism relevance to YepBio''s Parkinson''s programme.', 'Register promptly and identify speakers or attendees working on neurodegeneration and disease mechanisms.', 'YepBio UK opportunities | Complexity of Neural Function')
  ), inserted as (
    insert into public.schedule_items (title, description, item_type, visibility_scope, attendance_rule, starts_at, ends_at, time_precision, location, event_url, cost_type, cost_note, status, booking_status, priority, fit, next_action, source_note, created_by)
    select title, description, 'third_party', 'selected_organisations', 'optional', starts_at, ends_at, time_precision, location, event_url, cost_type, cost_note, 'proposed', 'to_register', priority, fit, next_action, source_note, admin_id
    from events event
    where not exists (select 1 from public.schedule_items existing where existing.title = event.title and existing.starts_at = event.starts_at)
    returning id
  )
  insert into public.schedule_item_organisations (schedule_item_id, organisation_id)
  select id, yepbio_id from inserted
  on conflict do nothing;

  insert into public.schedule_item_organisations (schedule_item_id, organisation_id)
  select item.id, yepbio_id
  from public.schedule_items item
  where item.source_note like 'YepBio UK opportunities | %'
    and not exists (select 1 from public.schedule_item_organisations target where target.schedule_item_id = item.id and target.organisation_id = yepbio_id);

  insert into public.event_responses (schedule_item_id, organisation_id, decision, updated_by)
  select item.id, yepbio_id, 'undecided', admin_id
  from public.schedule_items item
  where item.source_note like 'YepBio UK opportunities | %'
  on conflict (schedule_item_id, organisation_id) do nothing;
end $$;
